### ISSUE TITLE
javaslang-pure module compilation fails on Windows

### ISSUE THREAD

**Issue by ruslansennov** [javaslang/javaslang#1178]
mvn clean test
```
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Javaslang Pure 2.0.0-RC5-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.6.1:clean (default-clean) @ javaslang-pure ---
[INFO] Deleting C:\Users\rsennov\javaslang\javaslang-pure\target
[INFO]
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ javaslang-pure ---
[INFO]
[INFO] --- build-helper-maven-plugin:1.9.1:add-source (add-source) @ javaslang-pure ---
[INFO] Source directory: C:\Users\rsennov\javaslang\javaslang-pure\src-gen\main\java added.
[INFO]
[INFO] --- build-helper-maven-plugin:1.9.1:add-test-source (add-test-source) @ javaslang-pure ---
[INFO] Test Source directory: C:\Users\rsennov\javaslang\javaslang-pure\src-gen\test\java added.
[INFO]
[INFO] --- maven-clean-plugin:2.6.1:clean (clean-generated-sources) @ javaslang-pure ---
[INFO] Deleting C:\Users\rsennov\javaslang\javaslang-pure\src-gen (includes = [], excludes = [])
[INFO]
[INFO] --- scala-maven-plugin:3.2.2:script (default) @ javaslang-pure ---

[INFO]
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ javaslang-pure ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\rsennov\javaslang\javaslang-pure\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.2:compile (default-compile) @ javaslang-pure ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 7 source files to C:\Users\rsennov\javaslang\javaslang-pure\target\classes
[INFO]
[INFO] --- maven-bundle-plugin:3.0.1:manifest (bundle-manifest) @ javaslang-pure ---
[INFO]
[INFO] --- maven-resources-plugin:2.5:testResources (default-testResources) @ javaslang-pure ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\rsennov\javaslang\javaslang-pure\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.2:testCompile (default-testCompile) @ javaslang-pure ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to C:\Users\rsennov\javaslang\javaslang-pure\target\test-classes
An exception has occurred in the compiler (1.8.0_45). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  af
ter checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
java.lang.AssertionError: attribution shouldn't be happening here
        at com.sun.tools.javac.util.Assert.error(Assert.java:133)
        at com.sun.tools.javac.util.Assert.check(Assert.java:94)
        at com.sun.tools.javac.comp.DeferredAttr$DeferredAttrNode.process(DeferredAttr.java:591)
        at com.sun.tools.javac.comp.DeferredAttr$DeferredAttrContext.complete(DeferredAttr.java:479)
        at com.sun.tools.javac.comp.Infer.instantiateMethod(Infer.java:182)
        at com.sun.tools.javac.comp.Resolve.rawInstantiate(Resolve.java:567)
        at com.sun.tools.javac.comp.Resolve.checkMethod(Resolve.java:604)
        at com.sun.tools.javac.comp.Attr.checkMethod(Attr.java:3797)
        at com.sun.tools.javac.comp.Attr.checkIdInternal(Attr.java:3584)
        at com.sun.tools.javac.comp.Attr.checkMethodIdInternal(Attr.java:3491)
        at com.sun.tools.javac.comp.Attr.checkMethodId(Attr.java:3470)
        at com.sun.tools.javac.comp.Attr.checkId(Attr.java:3457)
        at com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:3339)
        at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897)
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:566)
        at com.sun.tools.javac.comp.Attr.visitApply(Attr.java:1806)
        at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1465)
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:566)
        at com.sun.tools.javac.comp.DeferredAttr.attribSpeculative(DeferredAttr.java:386)
        at com.sun.tools.javac.comp.DeferredAttr$2.complete(DeferredAttr.java:279)
        at com.sun.tools.javac.comp.DeferredAttr$DeferredType.check(DeferredAttr.java:245)
        at com.sun.tools.javac.comp.DeferredAttr$DeferredType.check(DeferredAttr.java:232)
        at com.sun.tools.javac.comp.Resolve$MethodResultInfo.check(Resolve.java:1003)
        at com.sun.tools.javac.comp.Resolve$4.checkArg(Resolve.java:829)
        at com.sun.tools.javac.comp.Resolve$AbstractMethodCheck.argumentsAcceptable(Resolve.java:734)
        at com.sun.tools.javac.comp.Resolve$4.argumentsAcceptable(Resolve.java:838)
        at com.sun.tools.javac.comp.Resolve.rawInstantiate(Resolve.java:579)
        at com.sun.tools.javac.comp.Resolve.selectBest(Resolve.java:1441)
        at com.sun.tools.javac.comp.Resolve.findFun(Resolve.java:1862)
        at com.sun.tools.javac.comp.Resolve$8.doLookup(Resolve.java:2393)
        at com.sun.tools.javac.comp.Resolve$BasicLookupHelper.lookup(Resolve.java:3084)
        at com.sun.tools.javac.comp.Resolve.lookupMethod(Resolve.java:3335)
        at com.sun.tools.javac.comp.Resolve.lookupMethod(Resolve.java:3320)
        at com.sun.tools.javac.comp.Resolve.resolveMethod(Resolve.java:2389)
        at com.sun.tools.javac.comp.Attr.visitIdent(Attr.java:3134)
        at com.sun.tools.javac.tree.JCTree$JCIdent.accept(JCTree.java:2011)
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:566)
        at com.sun.tools.javac.comp.Attr.visitApply(Attr.java:1806)
        at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1465)
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:566)
        at com.sun.tools.javac.comp.Attr.visitSelect(Attr.java:3218)
        at com.sun.tools.javac.tree.JCTree$JCFieldAccess.accept(JCTree.java:1897)
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:566)
        at com.sun.tools.javac.comp.Attr.visitApply(Attr.java:1806)
        at com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1465)
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:566)
        at com.sun.tools.javac.comp.Attr.attribExpr(Attr.java:615)
        at com.sun.tools.javac.comp.Attr.visitExec(Attr.java:1574)
        at com.sun.tools.javac.tree.JCTree$JCExpressionStatement.accept(JCTree.java:1296)
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:566)
        at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:635)
        at com.sun.tools.javac.comp.Attr.attribStats(Attr.java:651)
        at com.sun.tools.javac.comp.Attr.visitBlock(Attr.java:1105)
        at com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:909)
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:566)
        at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:635)
        at com.sun.tools.javac.comp.Attr.visitMethodDef(Attr.java:994)
        at com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:778)
        at com.sun.tools.javac.comp.Attr.attribTree(Attr.java:566)
        at com.sun.tools.javac.comp.Attr.attribStat(Attr.java:635)
        at com.sun.tools.javac.comp.Attr.attribClassBody(Attr.java:4330)
        at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4240)
        at com.sun.tools.javac.comp.Attr.attribClass(Attr.java:4169)
        at com.sun.tools.javac.comp.Attr.attrib(Attr.java:4144)
        at com.sun.tools.javac.main.JavaCompiler.attribute(JavaCompiler.java:1248)
        at com.sun.tools.javac.main.JavaCompiler.compile2(JavaCompiler.java:901)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:860)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
        at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
        at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:125)
        at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:169)
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:823)
        at org.apache.maven.plugin.compiler.TestCompilerMojo.execute(TestCompilerMojo.java:153)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] An unknown compilation problem occurred
[INFO] 1 error
```

**Comment by danieldietrich** [comment]
We should test it also with jdk 1.8.0_51 or greater. The 1.8.0_4x series had bugs...

**Comment by ruslansennov** [comment]
The problem located in exactly one test method

Compiles fine
```java
@Test
public void shouldFoldMultipleElements() {
    assertThat(Monoid.fold(Monoid.<Integer>of(0, (a, b) -> a + b), List.of(1, 2, 3))).isEqualTo(6);
}
```

Compilation fails
```java
@Test
public void shouldFoldMultipleElements() {
    assertThat(Monoid.fold(Monoid.of(0, (a, b) -> a + b), List.of(1, 2, 3))).isEqualTo(6);
}
```

**Comment by danieldietrich** [comment]
Maybe also a JDK problem with version < 1.8.0_51? I think this is a JDK bug. However, we need to fix it in the tests.

**Comment by ruslansennov** [comment]
I'll prepare patch in few minutes

**Comment by danieldietrich** [comment]
Cool, thx!
