### ISSUE TITLE
Clarify the decision to introduce ${value}

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1232]
It is easy to create an example that fails to match a Predicate:

```java
Predicate<Integer> p = i -> true;
Match(p).of(
    Case($(p), 1)
);
```

when this code runs it throws:

```java
Exception in thread "main" java.lang.ClassCastException: javaslang.Test$$Lambda$1/122883338 cannot be cast to java.lang.Integer
	at javaslang.API$2.apply(API.java:779)
	at javaslang.API$2.apply(API.java:776)
	at javaslang.API$Match$Case0.apply(API.java:835)
	at javaslang.API$Match$Case0.apply(API.java:823)
	at javaslang.API$Match.option(API.java:809)
	at javaslang.API$Match.of(API.java:800)
	at javaslang.Test.main(Test.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

That's because ${p} is interpreted as _predicate_ and not as _value_. But that is ok. Matching functions, especially predicates, makes no sense because function equality is indistinguishable in a computational setting. We had to check for (theoretically) infinite arguments, if the outcome of the compared functions are the same, which is not possible.

If the hashCodes of predicates(!) should be compared, we have to write `is(p)` instead of `$(p)`:

```java
Predicate<Integer> p = i -> true;
Match(p).of(
    Case(is(p), 1)
);
```

The result now is

```java
1
```

**Comment by danieldietrich** [comment]
## Retest after #1246 has been implemented!

There is a chance that this issue is obsolete then.
