### ISSUE TITLE
map() broken for Multimap backed by SortedSet with comparator

### ISSUE THREAD

**Issue by docent** [javaslang/javaslang#1466]
map() throws exception when called on a `Multimap` backed by a `SortedSet` with a custom comparator, e.g.:

``` java
Multimap<String, Thread> m = HashMultimap.withSortedSet(Comparator.comparing(Thread::getName))
                .of("t1", new Thread("t1c"), "t1", new Thread("t1b"));
m.map(t -> t);
```

It complains about V not implementing `Comparable`:

```
java.lang.ClassCastException: java.lang.Thread cannot be cast to java.lang.Comparable
    at javaslang.Tuple2.compareTo(Tuple2.java:81)
    at javaslang.Tuple2.compareTo(Tuple2.java:97)
    at javaslang.Tuple2.compareTo(Tuple2.java:29)
    at javaslang.collection.Comparators.lambda$naturalComparator$7c28a3e$1(Comparators.java:30)
    at javaslang.collection.RedBlackTreeModule$Node.insert(RedBlackTree.java:656)
    at javaslang.collection.RedBlackTree.insert(RedBlackTree.java:97)
    at javaslang.collection.RedBlackTree.ofAll(RedBlackTree.java:84)
    at javaslang.collection.TreeSet.ofAll(TreeSet.java:206)
    at javaslang.collection.TreeSet.map(TreeSet.java:715)
    at javaslang.collection.TreeSet.map(TreeSet.java:720)
    at javaslang.collection.TreeSet.map(TreeSet.java:32)
    at javaslang.collection.AbstractMultimap.lambda$iterator$9(AbstractMultimap.java:303)
    at javaslang.collection.Iterator$35.hasNext(Iterator.java:1487)
    at javaslang.collection.Iterator.map(Iterator.java:1578)
    at javaslang.collection.Multimap.map(Multimap.java:389)
```

This also breaks `toString()` on such multimaps.

**Comment by valery1707** [comment]
I confirm such behavior - trying to fix

**Comment by valery1707** [comment]
Internally TreeSet mapped from `V` into `Tuple<K, V>` and this tuples compared between each other. Tuple trying compare values directly, but values not comparable.

**Comment by danieldietrich** [comment]
@docent thanks for reporting!
@valery1707 thanks for the analysis! Need to check the code - this is a general problem.

I will be on holiday in one day (for 4 weeks...) - I will have my notebook with me ;-)

**Comment by ruslansennov** [comment]
@danieldietrich @valery1707 
It seems this issue can be solved by replacing current `AbstractMultimap.iterator()` implementation
```java
@Override
public Iterator<Tuple2<K, V>> iterator() {
    return back.iterator().flatMap(t -> t._2.map(v -> Tuple.of(t._1, v)));
}
```
to modified one
```java
@Override
public Iterator<Tuple2<K, V>> iterator() {
    return back.iterator().flatMap(t -> t._2.iterator().map(v -> Tuple.of(t._1, v)));
}
```
Here `t._2.iterator().` hides container type and the comparator is no longer needed

**Comment by danieldietrich** [comment]
Yes, that looks like a good solution!

**Comment by danieldietrich** [comment]
Fixed by @ruslansennov
