### ISSUE TITLE
Future execution vs. ExecutorService shutdown

### ISSUE THREAD

**Issue by danieldietrich** [javaslang/javaslang#1877]
@sshark provided an example that worked in Scala but did not work in Javaslang (see [Gitter post](https://gitter.im/javaslang/javaslang?at=58ac05a900c00c3d4f68788e)):

Scala:

```scala
 override def main(args: Array[String]) = {
    println(s"Running... ${ScarletFuture.getClass.getName}")

    val sleepMillis = 2000

    val bigF: Future[Unit] = Future {
      Try(Thread.sleep(sleepMillis))
      Option(10).foreach(foo)   // `#1`
    }

    bigF.map(_ => "BigF is fine")
      .recover{case t => "BigF is facing some trouble"}
      .foreach(println)


    Await.ready(bigF, 10 seconds)
```

Javaslang:

```java
public static void main(String[] args) {
    System.out.println("Running...");
    final long sleepMillis = 1500;

    Future<Void> bigF = Future.run(() -> {
        Try.run(() -> Thread.sleep(sleepMillis));
        Option.of(-100).toTry().flatMap(t -> Try.run(() -> foo(t))).getOrElseThrow(Function.identity());
    });

    Try.run(() -> Thread.sleep(sleepMillis + 500)); // #1

    bigF.map(t -> "BigF is ok")
        .recover(t -> "BigF is facing some problem")
        .forEach(System.out::println);

    ExecutorService executorService = bigF.executorService();

    System.out.println("Shutdown...");
    executorService.shutdown();
    executorService.awaitTermination(Long.MAX_VALUE, TimeUnit.MILLISECONDS);
}
```

Removing the lines `#1` makes the difference. Javaslang does not print "BigG is ok", Scala does.

**Comment by danieldietrich** [comment]
@sshark I can reproduce it in Scala. There is one difference:

* Java's `ExecutorService` silently does not accept more tasks when shutdown() was called
* Scala's `ExecutionContext` throws an exception when a Future tries to execute new Tasks and the underlying ExecutorService was shutdown

```scala
import scala.concurrent._
import scala.util._

object FutureTest {

  def main(args: Array[String]): Unit = {

    val executorService = java.util.concurrent.Executors.newCachedThreadPool()
    implicit val executionContext = ExecutionContext fromExecutorService executorService

    println("Running...")
    val sleepMillis = 1500

    val bigF: Future[String] = Future {
        Try(() -> Thread.sleep(sleepMillis))
        Success(-100).flatMap(t => Try(foo(t))).getOrElse(throw new Error())
    }

    // Try { Thread.sleep(sleepMillis + 500) } // #1

    bigF.map(t => "BigF is ok")
        .recover { case _ => "BigF is facing some problem" }
        .foreach(println)

    println("Shutdown...")
    executorService.shutdown()
    executorService.awaitTermination(3, java.util.concurrent.TimeUnit.SECONDS)
  }

  def foo(i: Int) = i.toString

}
```

This is the output when line \#1 is commented out:

```bash
Running...
Shutdown...
java.util.concurrent.RejectedExecutionException: Task scala.concurrent.impl.CallbackRunnable@24135fa8 rejected from java.util.concurrent.ThreadPoolExecutor@34c42156[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
	at scala.concurrent.impl.ExecutionContextImpl$$anon$1.execute(ExecutionContextImpl.scala:159)
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:284)
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:284)
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:284)
	at scala.concurrent.Promise.complete(Promise.scala:49)
	at scala.concurrent.Promise.complete$(Promise.scala:48)
	at scala.concurrent.impl.Promise$DefaultPromise.complete(Promise.scala:183)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

This is the output when line \#1 is executed:

```bash
```

**Comment by danieldietrich** [comment]
**Summary:**

Without line \#1 (waiting some millis for bigF to complete) the following happens:

1. The Future bigF is created
2. bigF is mapped to "BigF is ok". bigF isn't completed yet. Internally a Promise is created. The Promise has an underlying Future which will run as soon as bigF is completed.
3. The ExecutorService is shutdown. Especially it accepts no new Futures.
4. Eventually bigF completes. The crucial part: The promise cannot run the mapper "BigF is ok" because the ExecutorService does not accept new tasks.

The only way to first execute all tasks and then shutdown is to initiate shutdown when the Future is completed (Javaslang example):

```java
static void waitAndShutdown(ExecutorService executorService, Future<?>... futures) {
    Future.sequence(executorService, List.of(futures))
          .onComplete(ignored -> Try.run(() -> {
              executorService.shutdown();
              executorService.awaitTermination(3, TimeUnit.SECONDS);
          }));
}
```

**Comment by danieldietrich** [comment]
I will close the issue because Scala's Future and Javaslang's Future behave the same.
