### ISSUE TITLE
NPE thrown while combining Stream.groupBy with Map.map

### ISSUE THREAD

**Issue by patrox** [javaslang/javaslang#503]
While working on one of Euler problems I've found a nasty bug,
for now I've isolated it in a test and I'm working on a fix for it,
please see below for the details.

The following (not yet existing in master) test is failing:

```java
@Test
public void shouldGroupByAndMapProperly() {
   assertThat(Stream.of(1)
      .groupBy(Function.identity())
      .map(entry -> entry.key)
      .toList()).isEqualTo(List.of(1));
}
```
```
java.lang.NullPointerException
	at javaslang.collection.StreamTest.shouldGroupByAndMapProperly(StreamTest.java:294)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```
whereas, the corresponding scala code produces the expected results, without any problems:

```scala
Stream(1)
  .groupBy(e => e)
  .map(entry => entry._1)
  .toList
```

```
List[Int] = List(1)
```

**Comment by patrox** [comment]
Hahaha, I've found what's "wrong", it seems that the `HashMap.map` is rather simplistic:

https://github.com/javaslang/javaslang/blob/master/src/main/java/javaslang/collection/HashMap.java#L259

I'll try to add something more there, so I can continue with eating our own dog food :)
https://en.wikipedia.org/wiki/Eating_your_own_dog_food

**Comment by danieldietrich** [comment]
Yes, there are many unfinished methods in our collections. I will mark them this evening as TODO and work on implementations. With SortedSet (and SortedMap) there is even more TODO - the delete method of the Red-Black Tree is still missing. I will work on that.
Thx!

**Comment by patrox** [comment]
I can work on implementing missing `HashMap` methods, here is a short sample:
https://github.com/javaslang/javaslang/pull/505

**Comment by danieldietrich** [comment]
Great, appreciated! Then you take HashMap. Do it on a seperate branch please. I need to do some tests later today because it is suspicious to me that we cannot use a wildcard in equals.

I think there is still s.th. wrong in HashArrayMappedTree.iterator() or Iterator.ofIterables()...

**Comment by danieldietrich** [comment]
(I will get the hands on my notebook in 5 hours...)

**Comment by patrox** [comment]
Yes, this was also a bit strange to me as well. Sure, the missing HashMap's methods will be done separately.

**Comment by patrox** [comment]
I propose to throw `UnsupportedOperationException` http://java.sun.com/javase/6/docs/api/java/lang/UnsupportedOperationException.html in such cases, as this might be more 'honest', then returning `null`.

**Comment by danieldietrich** [comment]
yes, let's do that, maybe also with message "TODO"
